plugins:
  - jekyll-paginate-v2
  - jekyll-polyglot
  - jekyll-minifier
languages:                   ["en", "es", "de", "it", "fr"]
default_lang:                "en"
exclude_from_localization:   ["assets", "images", "css", "README.md", "manifest.json", "humans.txt", "sitemap.xml"]
parallel_localization:       true
a_rootpage:                  "https://jamulus.io"
githubrepoeditbase:          "https://github.com/jamulussoftware/jamulussoftware.github.io/edit/changes"
kbnewpage:                   'https://github.com/jamulussoftware/jamuluswebsite/new/changes/_posts/?value=---%0Alayout%3A%20post%0Atitle%3A%20%22Your%20Title%22%0Alang%3A%20%22en%22%0Aauthor%3A%20%22YourName%22%0Aheading%3A%20%22Heading%22%0A---%0AName%20This%20File%20and%20edit%20the%20parameters%20above%21&message=New%20post'
exclude:                     ["README.md", "Gemfile.lock", "Gemfile", "CONTRIBUTING.md"]
jekyll-minifier:
  remove_intertag_spaces:    true
  remove_spaces_inside_tags: true
  remove_multi_spaces:       true
  compress_json:             true
  exclude:                   "sitemap.xml"
excerpt_separator: <!--more-->
permalink: /kb/:categories/:year/:month/:day/:title:output_ext
pagination:
  enabled: true
  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false
  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'
  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 4
  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/:num/index.html'

  title: ':title / :num'
  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0

  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true
 # Optional,omit or set both before and after to zero to disable.
 # Controls how the pagination trail for the paginated pages look like.
  trail:
    before: 2
    after: 3
