name: Sync release to changes
on:
  push:
    branches:
      - 'release'
jobs:
  sync-branch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: ${{ github.sha }} update from release
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: release
          target_branch: changes
          github_token: ${{ github.token }}
